networks:
  dev-net:
    driver: bridge
services:
  db:
    image: mysql:8.0
    container_name: my-mysql-db
    networks:
      - dev-net
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER} 
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data_dev:/var/lib/mysql 
    ports:  
      - "3307:3306"

volumes:
  db_data_dev: