
#### get all posts
GET  http://localhost:8080/api/v1/posts/
Accept: application/json

### get post by id
GET  http://localhost:8080/api/v1/posts/1
Accept: application/json

### delete post by id (only admin)
DELETE   http://localhost:8080/api/v1/posts/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJyb2xlIjoibWVtYmVyIiwic3ViIjoiYWNjZXNzX3Rva2VuIiwiZXhwIjoxNzU5MDExMjQ2LCJpYXQiOjE3NTkwMTAzNDZ9.P_vA3DG4AWOMTLiUMy5XEnje8ZsbX6rCYBF6UJeyTo8
Accept: application/json

### create new post (only admin and member)
POST  http://localhost:8080/api/v1/posts HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJyb2xlIjoibWVtYmVyIiwic3ViIjoiYWNjZXNzX3Rva2VuIiwiZXhwIjoxNzU5MDExMjQ2LCJpYXQiOjE3NTkwMTAzNDZ9.P_vA3DG4AWOMTLiUMy5XEnje8ZsbX6rCYBF6UJeyTo8
 
{
  "author": "john doe ",
  "title": "New Post",
  "content": "This is a new post."
}

### get all users (only admin)
GET   http://localhost:8080/api/v1/users HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJyb2xlIjoibWVtYmVyIiwic3ViIjoiYWNjZXNzX3Rva2VuIiwiZXhwIjoxNzU5MDExMjQ2LCJpYXQiOjE3NTkwMTAzNDZ9.P_vA3DG4AWOMTLiUMy5XEnje8ZsbX6rCYBF6UJeyTo8
Accept: application/json


### register user
POST   http://localhost:8080/api/auth/register/ HTTP/1.1
Content-Type: : application/json

{
  "username":"admin ",
  "email":"admin@test.com",
  "password":"test123"
}

#### login user
POST   http://localhost:8080/api/auth/login HTTP/1.1
Content-Type: : application/json

{
  "email":"admin@test.com",
  "password":"test123"
}

### Refresh Token
POST http://localhost:8080/api/auth/refresh HTTP/1.1
Content-Type: application/json
Cookie: refresh_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJ0b2tlbl9pZCI6IjY0MjdkNzdlLTdjYzgtNDI1ZS1hODY2LWY3YTg4MmZmMjZhYyIsInN1YiI6InJlZnJlc2hfdG9rZW4iLCJleHAiOjE3NTk2NTA4NjMsImlhdCI6MTc1OTA0NjA2M30.IMMf3YDyIw_PuEnIk2oL2A_wjNn8AeovmWVU-fJEruc


### Wrong Refresh Token
POST http://localhost:8080/api/auth/refresh HTTP/1.1
Content-Type: application/json
Cookie: refresh_token=edsfdsfsdfOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJ0b2tlbl9pZCI6IjVkOGM1OTEzLTNhYmEtNGRhZi05MzM2LTJmMGJlMTUwZjY1YSIsInN1YiI6InJlZnJlc2hfdG9rZW4iLCJleHAiOjE3NTk2NDgwNTksImlhdCI6MTc1OTA0MzI1OX0.nUREtzjIKQHARyKiSjXZNA2aoLNGMM-8XI8t5HmWHy0



